# Generated by Django 2.2 on 2020-07-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('ip', models.CharField(max_length=120)),
                ('ie_browser', models.CharField(max_length=120)),
                ('created_time', models.DateTimeField()),
            ],
        ),
    ]
