# Generated by Django 2.2 on 2020-07-11 14:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddArticle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('public_time', models.DateTimeField()),
                ('part', models.CharField(max_length=200)),
                ('read_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
    ]
