# Generated by Django 2.2 on 2020-07-13 12:22

from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to=picture.models.path_and_rename, verbose_name='图片'),
        ),
    ]
